#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2024.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Apr 10 03:30:59 +07 2025
# SW Build 5076996 on Wed May 22 18:36:09 MDT 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim sim_top_u250_behav -key {Behavioral:sim_1:Functional:sim_top_u250} -tclbatch sim_top_u250.tcl -protoinst "protoinst_files/bd_021b.protoinst" -protoinst "protoinst_files/bd_ee24.protoinst" -protoinst "protoinst_files/memory_system.protoinst" -protoinst "protoinst_files/bd_a064.protoinst" -view /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/sim_top_u250_behav.wcfg -log simulate.log"
xsim sim_top_u250_behav -key {Behavioral:sim_1:Functional:sim_top_u250} -tclbatch sim_top_u250.tcl -protoinst "protoinst_files/bd_021b.protoinst" -protoinst "protoinst_files/bd_ee24.protoinst" -protoinst "protoinst_files/memory_system.protoinst" -protoinst "protoinst_files/bd_a064.protoinst" -view /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/sim_top_u250_behav.wcfg -log simulate.log

