# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.srcs/sources_1/bd/memory_system/ip/memory_system_axi_traffic_gen_0_0/memory_system_axi_traffic_gen_0_0.xci
# IP: The module: 'memory_system_axi_traffic_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_axi_traffic_gen_0_0/memory_system_axi_traffic_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'memory_system_axi_traffic_gen_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.srcs/sources_1/bd/memory_system/ip/memory_system_axi_traffic_gen_0_0/memory_system_axi_traffic_gen_0_0.xci
# IP: The module: 'memory_system_axi_traffic_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_axi_traffic_gen_0_0/memory_system_axi_traffic_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'memory_system_axi_traffic_gen_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
