# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.srcs/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/memory_system_ddr4_0_0.xci
# IP: The module: 'memory_system_ddr4_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/ip_0/memory_system_ddr4_0_0_microblaze_mcs.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==memory_system_ddr4_0_0_microblaze_mcs || ORIG_REF_NAME==memory_system_ddr4_0_0_microblaze_mcs} -quiet] -quiet

# Block Designs: /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/bd_0/bd_021b.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_021b || ORIG_REF_NAME==bd_021b} -quiet] -quiet

# IP: /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/bd_0/ip/ip_0/bd_021b_microblaze_I_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_021b_microblaze_I_0 || ORIG_REF_NAME==bd_021b_microblaze_I_0} -quiet] -quiet

# IP: /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/bd_0/ip/ip_1/bd_021b_rst_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_021b_rst_0_0 || ORIG_REF_NAME==bd_021b_rst_0_0} -quiet] -quiet

# IP: /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/bd_0/ip/ip_2/bd_021b_ilmb_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_021b_ilmb_0 || ORIG_REF_NAME==bd_021b_ilmb_0} -quiet] -quiet

# IP: /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/bd_0/ip/ip_3/bd_021b_dlmb_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_021b_dlmb_0 || ORIG_REF_NAME==bd_021b_dlmb_0} -quiet] -quiet

# IP: /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/bd_0/ip/ip_4/bd_021b_dlmb_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_021b_dlmb_cntlr_0 || ORIG_REF_NAME==bd_021b_dlmb_cntlr_0} -quiet] -quiet

# IP: /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/bd_0/ip/ip_5/bd_021b_ilmb_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_021b_ilmb_cntlr_0 || ORIG_REF_NAME==bd_021b_ilmb_cntlr_0} -quiet] -quiet

# IP: /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/bd_0/ip/ip_6/bd_021b_lmb_bram_I_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_021b_lmb_bram_I_0 || ORIG_REF_NAME==bd_021b_lmb_bram_I_0} -quiet] -quiet

# IP: /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/bd_0/ip/ip_7/bd_021b_second_dlmb_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_021b_second_dlmb_cntlr_0 || ORIG_REF_NAME==bd_021b_second_dlmb_cntlr_0} -quiet] -quiet

# IP: /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/bd_0/ip/ip_8/bd_021b_second_ilmb_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_021b_second_ilmb_cntlr_0 || ORIG_REF_NAME==bd_021b_second_ilmb_cntlr_0} -quiet] -quiet

# IP: /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/bd_0/ip/ip_9/bd_021b_second_lmb_bram_I_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_021b_second_lmb_bram_I_0 || ORIG_REF_NAME==bd_021b_second_lmb_bram_I_0} -quiet] -quiet

# IP: /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/bd_0/ip/ip_10/bd_021b_iomodule_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_021b_iomodule_0_0 || ORIG_REF_NAME==bd_021b_iomodule_0_0} -quiet] -quiet

# IP: /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/memory_system_ddr4_0_0_phy.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==memory_system_ddr4_0_0_phy || ORIG_REF_NAME==memory_system_ddr4_0_0_phy} -quiet] -quiet

# XDC: /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/bd_0/ip/ip_0/bd_021b_microblaze_I_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_021b_microblaze_I_0 || ORIG_REF_NAME==bd_021b_microblaze_I_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/bd_0/ip/ip_0/bd_021b_microblaze_I_0_ooc_debug.xdc

# XDC: /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/bd_0/ip/ip_1/bd_021b_rst_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_021b_rst_0_0 || ORIG_REF_NAME==bd_021b_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/bd_0/ip/ip_1/bd_021b_rst_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_021b_rst_0_0 || ORIG_REF_NAME==bd_021b_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/bd_0/ip/ip_2/bd_021b_ilmb_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_021b_ilmb_0 || ORIG_REF_NAME==bd_021b_ilmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/bd_0/ip/ip_3/bd_021b_dlmb_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_021b_dlmb_0 || ORIG_REF_NAME==bd_021b_dlmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/bd_0/ip/ip_6/bd_021b_lmb_bram_I_0_ooc.xdc

# XDC: /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/bd_0/ip/ip_9/bd_021b_second_lmb_bram_I_0_ooc.xdc

# XDC: /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/bd_0/ip/ip_10/bd_021b_iomodule_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_021b_iomodule_0_0 || ORIG_REF_NAME==bd_021b_iomodule_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/bd_0/bd_021b_ooc.xdc

# XDC: /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/ip_0/memory_system_ddr4_0_0_microblaze_mcs_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==memory_system_ddr4_0_0_microblaze_mcs || ORIG_REF_NAME==memory_system_ddr4_0_0_microblaze_mcs} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/ip_0/memory_system_ddr4_0_0_microblaze_mcs_ooc.xdc

# XDC: /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/par/memory_system_ddr4_0_0_phy_ooc.xdc

# XDC: /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/memory_system_ddr4_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'memory_system_ddr4_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/par/memory_system_ddr4_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'memory_system_ddr4_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.srcs/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/memory_system_ddr4_0_0.xci
# IP: The module: 'memory_system_ddr4_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/ip_0/memory_system_ddr4_0_0_microblaze_mcs.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==memory_system_ddr4_0_0_microblaze_mcs || ORIG_REF_NAME==memory_system_ddr4_0_0_microblaze_mcs} -quiet] -quiet

# Block Designs: /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/bd_0/bd_021b.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_021b || ORIG_REF_NAME==bd_021b} -quiet] -quiet

# IP: /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/bd_0/ip/ip_0/bd_021b_microblaze_I_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_021b_microblaze_I_0 || ORIG_REF_NAME==bd_021b_microblaze_I_0} -quiet] -quiet

# IP: /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/bd_0/ip/ip_1/bd_021b_rst_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_021b_rst_0_0 || ORIG_REF_NAME==bd_021b_rst_0_0} -quiet] -quiet

# IP: /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/bd_0/ip/ip_2/bd_021b_ilmb_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_021b_ilmb_0 || ORIG_REF_NAME==bd_021b_ilmb_0} -quiet] -quiet

# IP: /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/bd_0/ip/ip_3/bd_021b_dlmb_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_021b_dlmb_0 || ORIG_REF_NAME==bd_021b_dlmb_0} -quiet] -quiet

# IP: /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/bd_0/ip/ip_4/bd_021b_dlmb_cntlr_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_021b_dlmb_cntlr_0 || ORIG_REF_NAME==bd_021b_dlmb_cntlr_0} -quiet] -quiet

# IP: /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/bd_0/ip/ip_5/bd_021b_ilmb_cntlr_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_021b_ilmb_cntlr_0 || ORIG_REF_NAME==bd_021b_ilmb_cntlr_0} -quiet] -quiet

# IP: /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/bd_0/ip/ip_6/bd_021b_lmb_bram_I_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_021b_lmb_bram_I_0 || ORIG_REF_NAME==bd_021b_lmb_bram_I_0} -quiet] -quiet

# IP: /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/bd_0/ip/ip_7/bd_021b_second_dlmb_cntlr_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_021b_second_dlmb_cntlr_0 || ORIG_REF_NAME==bd_021b_second_dlmb_cntlr_0} -quiet] -quiet

# IP: /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/bd_0/ip/ip_8/bd_021b_second_ilmb_cntlr_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_021b_second_ilmb_cntlr_0 || ORIG_REF_NAME==bd_021b_second_ilmb_cntlr_0} -quiet] -quiet

# IP: /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/bd_0/ip/ip_9/bd_021b_second_lmb_bram_I_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_021b_second_lmb_bram_I_0 || ORIG_REF_NAME==bd_021b_second_lmb_bram_I_0} -quiet] -quiet

# IP: /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/bd_0/ip/ip_10/bd_021b_iomodule_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_021b_iomodule_0_0 || ORIG_REF_NAME==bd_021b_iomodule_0_0} -quiet] -quiet

# IP: /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/memory_system_ddr4_0_0_phy.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==memory_system_ddr4_0_0_phy || ORIG_REF_NAME==memory_system_ddr4_0_0_phy} -quiet] -quiet

# XDC: /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/bd_0/ip/ip_0/bd_021b_microblaze_I_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_021b_microblaze_I_0 || ORIG_REF_NAME==bd_021b_microblaze_I_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/bd_0/ip/ip_0/bd_021b_microblaze_I_0_ooc_debug.xdc

# XDC: /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/bd_0/ip/ip_1/bd_021b_rst_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_021b_rst_0_0 || ORIG_REF_NAME==bd_021b_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/bd_0/ip/ip_1/bd_021b_rst_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_021b_rst_0_0 || ORIG_REF_NAME==bd_021b_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/bd_0/ip/ip_2/bd_021b_ilmb_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_021b_ilmb_0 || ORIG_REF_NAME==bd_021b_ilmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/bd_0/ip/ip_3/bd_021b_dlmb_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_021b_dlmb_0 || ORIG_REF_NAME==bd_021b_dlmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/bd_0/ip/ip_6/bd_021b_lmb_bram_I_0_ooc.xdc

# XDC: /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/bd_0/ip/ip_9/bd_021b_second_lmb_bram_I_0_ooc.xdc

# XDC: /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/bd_0/ip/ip_10/bd_021b_iomodule_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_021b_iomodule_0_0 || ORIG_REF_NAME==bd_021b_iomodule_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/bd_0/bd_021b_ooc.xdc

# XDC: /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/ip_0/memory_system_ddr4_0_0_microblaze_mcs_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==memory_system_ddr4_0_0_microblaze_mcs || ORIG_REF_NAME==memory_system_ddr4_0_0_microblaze_mcs} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/ip_0/memory_system_ddr4_0_0_microblaze_mcs_ooc.xdc

# XDC: /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/par/memory_system_ddr4_0_0_phy_ooc.xdc

# XDC: /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/memory_system_ddr4_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'memory_system_ddr4_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/par/memory_system_ddr4_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'memory_system_ddr4_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
