transcript off
onbreak {quit -force}
onerror {quit -force}
transcript on

vlib work
vlib activehdl/xilinx_vip
vlib activehdl/xpm
vlib activehdl/microblaze_v11_0_13
vlib activehdl/xil_defaultlib
vlib activehdl/lib_cdc_v1_0_3
vlib activehdl/proc_sys_reset_v5_0_15
vlib activehdl/lmb_v10_v3_0_14
vlib activehdl/lmb_bram_if_cntlr_v4_0_24
vlib activehdl/blk_mem_gen_v8_4_8
vlib activehdl/iomodule_v3_1_10
vlib activehdl/smartconnect_v1_0
vlib activehdl/axi_infrastructure_v1_1_0
vlib activehdl/axi_register_slice_v2_1_31
vlib activehdl/axi_vip_v1_1_17
vlib activehdl/xlconstant_v1_1_9
vlib activehdl/dist_mem_gen_v8_0_15
vlib activehdl/lib_bmg_v1_0_17
vlib activehdl/axi_traffic_gen_v3_0_17
vlib activehdl/util_vector_logic_v2_0_4
vlib activehdl/lib_pkg_v1_0_4
vlib activehdl/lib_srl_fifo_v1_0_4
vlib activehdl/fifo_generator_v13_2_10
vlib activehdl/lib_fifo_v1_0_19
vlib activehdl/axi_datamover_v5_1_33
vlib activehdl/axi_sg_v4_1_18
vlib activehdl/axi_cdma_v4_1_31

vmap xilinx_vip activehdl/xilinx_vip
vmap xpm activehdl/xpm
vmap microblaze_v11_0_13 activehdl/microblaze_v11_0_13
vmap xil_defaultlib activehdl/xil_defaultlib
vmap lib_cdc_v1_0_3 activehdl/lib_cdc_v1_0_3
vmap proc_sys_reset_v5_0_15 activehdl/proc_sys_reset_v5_0_15
vmap lmb_v10_v3_0_14 activehdl/lmb_v10_v3_0_14
vmap lmb_bram_if_cntlr_v4_0_24 activehdl/lmb_bram_if_cntlr_v4_0_24
vmap blk_mem_gen_v8_4_8 activehdl/blk_mem_gen_v8_4_8
vmap iomodule_v3_1_10 activehdl/iomodule_v3_1_10
vmap smartconnect_v1_0 activehdl/smartconnect_v1_0
vmap axi_infrastructure_v1_1_0 activehdl/axi_infrastructure_v1_1_0
vmap axi_register_slice_v2_1_31 activehdl/axi_register_slice_v2_1_31
vmap axi_vip_v1_1_17 activehdl/axi_vip_v1_1_17
vmap xlconstant_v1_1_9 activehdl/xlconstant_v1_1_9
vmap dist_mem_gen_v8_0_15 activehdl/dist_mem_gen_v8_0_15
vmap lib_bmg_v1_0_17 activehdl/lib_bmg_v1_0_17
vmap axi_traffic_gen_v3_0_17 activehdl/axi_traffic_gen_v3_0_17
vmap util_vector_logic_v2_0_4 activehdl/util_vector_logic_v2_0_4
vmap lib_pkg_v1_0_4 activehdl/lib_pkg_v1_0_4
vmap lib_srl_fifo_v1_0_4 activehdl/lib_srl_fifo_v1_0_4
vmap fifo_generator_v13_2_10 activehdl/fifo_generator_v13_2_10
vmap lib_fifo_v1_0_19 activehdl/lib_fifo_v1_0_19
vmap axi_datamover_v5_1_33 activehdl/axi_datamover_v5_1_33
vmap axi_sg_v4_1_18 activehdl/axi_sg_v4_1_18
vmap axi_cdma_v4_1_31 activehdl/axi_cdma_v4_1_31

vlog -work xilinx_vip  -sv2k12 "+incdir+/home/huy_k66/apps/tools/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_13 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_24 -l blk_mem_gen_v8_4_8 -l iomodule_v3_1_10 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_31 -l axi_vip_v1_1_17 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l lib_bmg_v1_0_17 -l axi_traffic_gen_v3_0_17 -l util_vector_logic_v2_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_cdma_v4_1_31 \
"/home/huy_k66/apps/tools/Vivado/2024.1/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
"/home/huy_k66/apps/tools/Vivado/2024.1/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
"/home/huy_k66/apps/tools/Vivado/2024.1/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
"/home/huy_k66/apps/tools/Vivado/2024.1/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
"/home/huy_k66/apps/tools/Vivado/2024.1/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
"/home/huy_k66/apps/tools/Vivado/2024.1/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
"/home/huy_k66/apps/tools/Vivado/2024.1/data/xilinx_vip/hdl/axi_vip_if.sv" \
"/home/huy_k66/apps/tools/Vivado/2024.1/data/xilinx_vip/hdl/clk_vip_if.sv" \
"/home/huy_k66/apps/tools/Vivado/2024.1/data/xilinx_vip/hdl/rst_vip_if.sv" \

vlog -work xpm  -sv2k12 "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/f0b6/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/c783/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/ec67/hdl" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/56ae/hdl/src/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+/home/huy_k66/apps/tools/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_13 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_24 -l blk_mem_gen_v8_4_8 -l iomodule_v3_1_10 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_31 -l axi_vip_v1_1_17 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l lib_bmg_v1_0_17 -l axi_traffic_gen_v3_0_17 -l util_vector_logic_v2_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_cdma_v4_1_31 \
"/home/huy_k66/apps/tools/Vivado/2024.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
"/home/huy_k66/apps/tools/Vivado/2024.1/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
"/home/huy_k66/apps/tools/Vivado/2024.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \

vcom -work xpm -  \
"/home/huy_k66/apps/tools/Vivado/2024.1/data/ip/xpm/xpm_VCOMP.vhd" \

vcom -work microblaze_v11_0_13 -  \
"../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/aa1c/hdl/microblaze_v11_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -  \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/bd_0/ip/ip_0/sim/bd_021b_microblaze_I_0.vhd" \

vcom -work lib_cdc_v1_0_3 -  \
"../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/2a4f/hdl/lib_cdc_v1_0_rfs.vhd" \

vcom -work proc_sys_reset_v5_0_15 -  \
"../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/3a26/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -  \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/bd_0/ip/ip_1/sim/bd_021b_rst_0_0.vhd" \

vcom -work lmb_v10_v3_0_14 -  \
"../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/7495/hdl/lmb_v10_v3_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -  \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/bd_0/ip/ip_2/sim/bd_021b_ilmb_0.vhd" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/bd_0/ip/ip_3/sim/bd_021b_dlmb_0.vhd" \

vcom -work lmb_bram_if_cntlr_v4_0_24 -  \
"../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/3eb2/hdl/lmb_bram_if_cntlr_v4_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -  \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/bd_0/ip/ip_4/sim/bd_021b_dlmb_cntlr_0.vhd" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/bd_0/ip/ip_5/sim/bd_021b_ilmb_cntlr_0.vhd" \

vlog -work blk_mem_gen_v8_4_8  -v2k5 "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/f0b6/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/c783/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/ec67/hdl" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/56ae/hdl/src/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+/home/huy_k66/apps/tools/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_13 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_24 -l blk_mem_gen_v8_4_8 -l iomodule_v3_1_10 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_31 -l axi_vip_v1_1_17 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l lib_bmg_v1_0_17 -l axi_traffic_gen_v3_0_17 -l util_vector_logic_v2_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_cdma_v4_1_31 \
"../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/09bd/simulation/blk_mem_gen_v8_4.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/f0b6/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/c783/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/ec67/hdl" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/56ae/hdl/src/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+/home/huy_k66/apps/tools/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_13 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_24 -l blk_mem_gen_v8_4_8 -l iomodule_v3_1_10 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_31 -l axi_vip_v1_1_17 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l lib_bmg_v1_0_17 -l axi_traffic_gen_v3_0_17 -l util_vector_logic_v2_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_cdma_v4_1_31 \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/bd_0/ip/ip_6/sim/bd_021b_lmb_bram_I_0.v" \

vcom -work xil_defaultlib -  \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/bd_0/ip/ip_7/sim/bd_021b_second_dlmb_cntlr_0.vhd" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/bd_0/ip/ip_8/sim/bd_021b_second_ilmb_cntlr_0.vhd" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/f0b6/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/c783/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/ec67/hdl" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/56ae/hdl/src/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+/home/huy_k66/apps/tools/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_13 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_24 -l blk_mem_gen_v8_4_8 -l iomodule_v3_1_10 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_31 -l axi_vip_v1_1_17 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l lib_bmg_v1_0_17 -l axi_traffic_gen_v3_0_17 -l util_vector_logic_v2_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_cdma_v4_1_31 \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/bd_0/ip/ip_9/sim/bd_021b_second_lmb_bram_I_0.v" \

vcom -work iomodule_v3_1_10 -  \
"../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/213d/hdl/iomodule_v3_1_vh_rfs.vhd" \

vcom -work xil_defaultlib -  \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/bd_0/ip/ip_10/sim/bd_021b_iomodule_0_0.vhd" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/f0b6/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/c783/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/ec67/hdl" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/56ae/hdl/src/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+/home/huy_k66/apps/tools/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_13 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_24 -l blk_mem_gen_v8_4_8 -l iomodule_v3_1_10 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_31 -l axi_vip_v1_1_17 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l lib_bmg_v1_0_17 -l axi_traffic_gen_v3_0_17 -l util_vector_logic_v2_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_cdma_v4_1_31 \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/bd_0/sim/bd_021b.v" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/ip_0/sim/memory_system_ddr4_0_0_microblaze_mcs.v" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/f0b6/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/c783/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/ec67/hdl" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/56ae/hdl/src/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+/home/huy_k66/apps/tools/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_13 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_24 -l blk_mem_gen_v8_4_8 -l iomodule_v3_1_10 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_31 -l axi_vip_v1_1_17 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l lib_bmg_v1_0_17 -l axi_traffic_gen_v3_0_17 -l util_vector_logic_v2_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_cdma_v4_1_31 \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/phy/memory_system_ddr4_0_0_phy_ddr4.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/phy/ddr4_phy_v2_2_xiphy_behav.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/phy/ddr4_phy_v2_2_xiphy.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/iob/ddr4_phy_v2_2_iob_byte.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/iob/ddr4_phy_v2_2_iob.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/clocking/ddr4_phy_v2_2_pll.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/xiphy_files/ddr4_phy_v2_2_xiphy_tristate_wrapper.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/xiphy_files/ddr4_phy_v2_2_xiphy_riuor_wrapper.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/xiphy_files/ddr4_phy_v2_2_xiphy_control_wrapper.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/xiphy_files/ddr4_phy_v2_2_xiphy_byte_wrapper.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/xiphy_files/ddr4_phy_v2_2_xiphy_bitslice_wrapper.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/ip_top/memory_system_ddr4_0_0_phy.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_wtr.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_ref.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_rd_wr.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_periodic.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_group.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_ecc_merge_enc.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_ecc_gen.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_ecc_fi_xor.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_ecc_dec_fix.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_ecc_buf.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_ecc.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_ctl.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_cmd_mux_c.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_cmd_mux_ap.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_arb_p.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_arb_mux_p.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_arb_c.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_arb_a.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_act_timer.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_act_rank.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/controller/ddr4_v2_2_mc.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ui/ddr4_v2_2_ui_wr_data.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ui/ddr4_v2_2_ui_rd_data.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ui/ddr4_v2_2_ui_cmd.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ui/ddr4_v2_2_ui.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_ar_channel.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_aw_channel.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_b_channel.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_cmd_arbiter.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_cmd_fsm.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_cmd_translator.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_fifo.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_incr_cmd.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_r_channel.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_w_channel.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_wr_cmd_fsm.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_wrap_cmd.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/axi/ddr4_v2_2_a_upsizer.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/axi/ddr4_v2_2_axi.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_register_slice.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_upsizer.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/axi/ddr4_v2_2_axic_register_slice.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/axi/ddr4_v2_2_carry_and.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/axi/ddr4_v2_2_carry_latch_and.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/axi/ddr4_v2_2_carry_latch_or.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/axi/ddr4_v2_2_carry_or.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/axi/ddr4_v2_2_command_fifo.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/axi/ddr4_v2_2_comparator.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/axi/ddr4_v2_2_comparator_sel.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/axi/ddr4_v2_2_comparator_sel_static.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/axi/ddr4_v2_2_r_upsizer.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/axi/ddr4_v2_2_w_upsizer.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/axi_ctrl/ddr4_v2_2_axi_ctrl_addr_decode.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/axi_ctrl/ddr4_v2_2_axi_ctrl_read.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/axi_ctrl/ddr4_v2_2_axi_ctrl_reg_bank.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/axi_ctrl/ddr4_v2_2_axi_ctrl_reg.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/axi_ctrl/ddr4_v2_2_axi_ctrl_top.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/axi_ctrl/ddr4_v2_2_axi_ctrl_write.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/clocking/ddr4_v2_2_infrastructure.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_xsdb_bram.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_write.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_wr_byte.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_wr_bit.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_sync.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_read.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_rd_en.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_pi.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_mc_odt.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_debug_microblaze.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_cplx_data.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_cplx.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_config_rom.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_addr_decode.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_top.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_xsdb_arbiter.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal/ddr4_v2_2_cal.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal/ddr4_v2_2_chipscope_xsdb_slave.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal/ddr4_v2_2_dp_AB9.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top/memory_system_ddr4_0_0_ddr4.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top/memory_system_ddr4_0_0_ddr4_mem_intfc.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal/memory_system_ddr4_0_0_ddr4_cal_riu.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top/memory_system_ddr4_0_0.sv" \
"../../../bd/memory_system/ip/memory_system_ddr4_0_0/tb/memory_system_ddr4_0_0_microblaze_mcs_0.sv" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/f0b6/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/c783/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/ec67/hdl" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/56ae/hdl/src/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+/home/huy_k66/apps/tools/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_13 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_24 -l blk_mem_gen_v8_4_8 -l iomodule_v3_1_10 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_31 -l axi_vip_v1_1_17 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l lib_bmg_v1_0_17 -l axi_traffic_gen_v3_0_17 -l util_vector_logic_v2_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_cdma_v4_1_31 \
"../../../bd/memory_system/ip/memory_system_smartconnect_0_0/bd_0/sim/bd_ee24.v" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/f0b6/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/c783/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/ec67/hdl" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/56ae/hdl/src/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+/home/huy_k66/apps/tools/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_13 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_24 -l blk_mem_gen_v8_4_8 -l iomodule_v3_1_10 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_31 -l axi_vip_v1_1_17 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l lib_bmg_v1_0_17 -l axi_traffic_gen_v3_0_17 -l util_vector_logic_v2_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_cdma_v4_1_31 \
"../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/f0b6/hdl/sc_util_v1_0_vl_rfs.sv" \
"../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/3718/hdl/sc_switchboard_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/f0b6/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/c783/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/ec67/hdl" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/56ae/hdl/src/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+/home/huy_k66/apps/tools/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_13 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_24 -l blk_mem_gen_v8_4_8 -l iomodule_v3_1_10 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_31 -l axi_vip_v1_1_17 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l lib_bmg_v1_0_17 -l axi_traffic_gen_v3_0_17 -l util_vector_logic_v2_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_cdma_v4_1_31 \
"../../../bd/memory_system/ip/memory_system_smartconnect_0_0/bd_0/ip/ip_0/sim/bd_ee24_arsw_0.sv" \
"../../../bd/memory_system/ip/memory_system_smartconnect_0_0/bd_0/ip/ip_1/sim/bd_ee24_rsw_0.sv" \
"../../../bd/memory_system/ip/memory_system_smartconnect_0_0/bd_0/ip/ip_2/sim/bd_ee24_awsw_0.sv" \
"../../../bd/memory_system/ip/memory_system_smartconnect_0_0/bd_0/ip/ip_3/sim/bd_ee24_wsw_0.sv" \
"../../../bd/memory_system/ip/memory_system_smartconnect_0_0/bd_0/ip/ip_4/sim/bd_ee24_bsw_0.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/f0b6/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/c783/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/ec67/hdl" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/56ae/hdl/src/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+/home/huy_k66/apps/tools/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_13 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_24 -l blk_mem_gen_v8_4_8 -l iomodule_v3_1_10 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_31 -l axi_vip_v1_1_17 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l lib_bmg_v1_0_17 -l axi_traffic_gen_v3_0_17 -l util_vector_logic_v2_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_cdma_v4_1_31 \
"../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/98d8/hdl/sc_mmu_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/f0b6/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/c783/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/ec67/hdl" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/56ae/hdl/src/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+/home/huy_k66/apps/tools/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_13 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_24 -l blk_mem_gen_v8_4_8 -l iomodule_v3_1_10 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_31 -l axi_vip_v1_1_17 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l lib_bmg_v1_0_17 -l axi_traffic_gen_v3_0_17 -l util_vector_logic_v2_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_cdma_v4_1_31 \
"../../../bd/memory_system/ip/memory_system_smartconnect_0_0/bd_0/ip/ip_5/sim/bd_ee24_s00mmu_0.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/f0b6/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/c783/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/ec67/hdl" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/56ae/hdl/src/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+/home/huy_k66/apps/tools/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_13 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_24 -l blk_mem_gen_v8_4_8 -l iomodule_v3_1_10 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_31 -l axi_vip_v1_1_17 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l lib_bmg_v1_0_17 -l axi_traffic_gen_v3_0_17 -l util_vector_logic_v2_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_cdma_v4_1_31 \
"../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/2da8/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/f0b6/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/c783/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/ec67/hdl" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/56ae/hdl/src/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+/home/huy_k66/apps/tools/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_13 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_24 -l blk_mem_gen_v8_4_8 -l iomodule_v3_1_10 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_31 -l axi_vip_v1_1_17 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l lib_bmg_v1_0_17 -l axi_traffic_gen_v3_0_17 -l util_vector_logic_v2_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_cdma_v4_1_31 \
"../../../bd/memory_system/ip/memory_system_smartconnect_0_0/bd_0/ip/ip_6/sim/bd_ee24_s00tr_0.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/f0b6/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/c783/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/ec67/hdl" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/56ae/hdl/src/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+/home/huy_k66/apps/tools/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_13 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_24 -l blk_mem_gen_v8_4_8 -l iomodule_v3_1_10 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_31 -l axi_vip_v1_1_17 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l lib_bmg_v1_0_17 -l axi_traffic_gen_v3_0_17 -l util_vector_logic_v2_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_cdma_v4_1_31 \
"../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/a950/hdl/sc_si_converter_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/f0b6/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/c783/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/ec67/hdl" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/56ae/hdl/src/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+/home/huy_k66/apps/tools/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_13 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_24 -l blk_mem_gen_v8_4_8 -l iomodule_v3_1_10 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_31 -l axi_vip_v1_1_17 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l lib_bmg_v1_0_17 -l axi_traffic_gen_v3_0_17 -l util_vector_logic_v2_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_cdma_v4_1_31 \
"../../../bd/memory_system/ip/memory_system_smartconnect_0_0/bd_0/ip/ip_7/sim/bd_ee24_s00sic_0.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/f0b6/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/c783/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/ec67/hdl" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/56ae/hdl/src/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+/home/huy_k66/apps/tools/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_13 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_24 -l blk_mem_gen_v8_4_8 -l iomodule_v3_1_10 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_31 -l axi_vip_v1_1_17 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l lib_bmg_v1_0_17 -l axi_traffic_gen_v3_0_17 -l util_vector_logic_v2_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_cdma_v4_1_31 \
"../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/cef3/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/f0b6/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/c783/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/ec67/hdl" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/56ae/hdl/src/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+/home/huy_k66/apps/tools/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_13 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_24 -l blk_mem_gen_v8_4_8 -l iomodule_v3_1_10 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_31 -l axi_vip_v1_1_17 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l lib_bmg_v1_0_17 -l axi_traffic_gen_v3_0_17 -l util_vector_logic_v2_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_cdma_v4_1_31 \
"../../../bd/memory_system/ip/memory_system_smartconnect_0_0/bd_0/ip/ip_8/sim/bd_ee24_s00a2s_0.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/f0b6/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/c783/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/ec67/hdl" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/56ae/hdl/src/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+/home/huy_k66/apps/tools/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_13 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_24 -l blk_mem_gen_v8_4_8 -l iomodule_v3_1_10 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_31 -l axi_vip_v1_1_17 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l lib_bmg_v1_0_17 -l axi_traffic_gen_v3_0_17 -l util_vector_logic_v2_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_cdma_v4_1_31 \
"../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/c783/hdl/sc_node_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/f0b6/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/c783/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/ec67/hdl" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/56ae/hdl/src/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+/home/huy_k66/apps/tools/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_13 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_24 -l blk_mem_gen_v8_4_8 -l iomodule_v3_1_10 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_31 -l axi_vip_v1_1_17 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l lib_bmg_v1_0_17 -l axi_traffic_gen_v3_0_17 -l util_vector_logic_v2_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_cdma_v4_1_31 \
"../../../bd/memory_system/ip/memory_system_smartconnect_0_0/bd_0/ip/ip_9/sim/bd_ee24_sarn_0.sv" \
"../../../bd/memory_system/ip/memory_system_smartconnect_0_0/bd_0/ip/ip_10/sim/bd_ee24_srn_0.sv" \
"../../../bd/memory_system/ip/memory_system_smartconnect_0_0/bd_0/ip/ip_11/sim/bd_ee24_sawn_0.sv" \
"../../../bd/memory_system/ip/memory_system_smartconnect_0_0/bd_0/ip/ip_12/sim/bd_ee24_swn_0.sv" \
"../../../bd/memory_system/ip/memory_system_smartconnect_0_0/bd_0/ip/ip_13/sim/bd_ee24_sbn_0.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/f0b6/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/c783/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/ec67/hdl" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/56ae/hdl/src/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+/home/huy_k66/apps/tools/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_13 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_24 -l blk_mem_gen_v8_4_8 -l iomodule_v3_1_10 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_31 -l axi_vip_v1_1_17 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l lib_bmg_v1_0_17 -l axi_traffic_gen_v3_0_17 -l util_vector_logic_v2_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_cdma_v4_1_31 \
"../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/7f4f/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/f0b6/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/c783/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/ec67/hdl" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/56ae/hdl/src/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+/home/huy_k66/apps/tools/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_13 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_24 -l blk_mem_gen_v8_4_8 -l iomodule_v3_1_10 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_31 -l axi_vip_v1_1_17 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l lib_bmg_v1_0_17 -l axi_traffic_gen_v3_0_17 -l util_vector_logic_v2_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_cdma_v4_1_31 \
"../../../bd/memory_system/ip/memory_system_smartconnect_0_0/bd_0/ip/ip_14/sim/bd_ee24_m00s2a_0.sv" \
"../../../bd/memory_system/ip/memory_system_smartconnect_0_0/bd_0/ip/ip_15/sim/bd_ee24_m00arn_0.sv" \
"../../../bd/memory_system/ip/memory_system_smartconnect_0_0/bd_0/ip/ip_16/sim/bd_ee24_m00rn_0.sv" \
"../../../bd/memory_system/ip/memory_system_smartconnect_0_0/bd_0/ip/ip_17/sim/bd_ee24_m00awn_0.sv" \
"../../../bd/memory_system/ip/memory_system_smartconnect_0_0/bd_0/ip/ip_18/sim/bd_ee24_m00wn_0.sv" \
"../../../bd/memory_system/ip/memory_system_smartconnect_0_0/bd_0/ip/ip_19/sim/bd_ee24_m00bn_0.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/f0b6/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/c783/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/ec67/hdl" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/56ae/hdl/src/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+/home/huy_k66/apps/tools/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_13 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_24 -l blk_mem_gen_v8_4_8 -l iomodule_v3_1_10 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_31 -l axi_vip_v1_1_17 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l lib_bmg_v1_0_17 -l axi_traffic_gen_v3_0_17 -l util_vector_logic_v2_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_cdma_v4_1_31 \
"../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/1f04/hdl/sc_exit_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/f0b6/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/c783/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/ec67/hdl" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/56ae/hdl/src/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+/home/huy_k66/apps/tools/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_13 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_24 -l blk_mem_gen_v8_4_8 -l iomodule_v3_1_10 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_31 -l axi_vip_v1_1_17 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l lib_bmg_v1_0_17 -l axi_traffic_gen_v3_0_17 -l util_vector_logic_v2_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_cdma_v4_1_31 \
"../../../bd/memory_system/ip/memory_system_smartconnect_0_0/bd_0/ip/ip_20/sim/bd_ee24_m00e_0.sv" \
"../../../bd/memory_system/ip/memory_system_smartconnect_0_0/bd_0/ip/ip_21/sim/bd_ee24_m01s2a_0.sv" \
"../../../bd/memory_system/ip/memory_system_smartconnect_0_0/bd_0/ip/ip_22/sim/bd_ee24_m01arn_0.sv" \
"../../../bd/memory_system/ip/memory_system_smartconnect_0_0/bd_0/ip/ip_23/sim/bd_ee24_m01rn_0.sv" \
"../../../bd/memory_system/ip/memory_system_smartconnect_0_0/bd_0/ip/ip_24/sim/bd_ee24_m01awn_0.sv" \
"../../../bd/memory_system/ip/memory_system_smartconnect_0_0/bd_0/ip/ip_25/sim/bd_ee24_m01wn_0.sv" \
"../../../bd/memory_system/ip/memory_system_smartconnect_0_0/bd_0/ip/ip_26/sim/bd_ee24_m01bn_0.sv" \
"../../../bd/memory_system/ip/memory_system_smartconnect_0_0/bd_0/ip/ip_27/sim/bd_ee24_m01e_0.sv" \

vlog -work axi_infrastructure_v1_1_0  -v2k5 "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/f0b6/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/c783/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/ec67/hdl" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/56ae/hdl/src/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+/home/huy_k66/apps/tools/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_13 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_24 -l blk_mem_gen_v8_4_8 -l iomodule_v3_1_10 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_31 -l axi_vip_v1_1_17 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l lib_bmg_v1_0_17 -l axi_traffic_gen_v3_0_17 -l util_vector_logic_v2_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_cdma_v4_1_31 \
"../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \

vlog -work axi_register_slice_v2_1_31  -v2k5 "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/f0b6/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/c783/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/ec67/hdl" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/56ae/hdl/src/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+/home/huy_k66/apps/tools/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_13 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_24 -l blk_mem_gen_v8_4_8 -l iomodule_v3_1_10 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_31 -l axi_vip_v1_1_17 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l lib_bmg_v1_0_17 -l axi_traffic_gen_v3_0_17 -l util_vector_logic_v2_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_cdma_v4_1_31 \
"../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/92b2/hdl/axi_register_slice_v2_1_vl_rfs.v" \

vlog -work axi_vip_v1_1_17  -sv2k12 "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/f0b6/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/c783/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/ec67/hdl" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/56ae/hdl/src/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+/home/huy_k66/apps/tools/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_13 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_24 -l blk_mem_gen_v8_4_8 -l iomodule_v3_1_10 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_31 -l axi_vip_v1_1_17 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l lib_bmg_v1_0_17 -l axi_traffic_gen_v3_0_17 -l util_vector_logic_v2_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_cdma_v4_1_31 \
"../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/4d04/hdl/axi_vip_v1_1_vl_rfs.sv" \

vlog -work xlconstant_v1_1_9  -v2k5 "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/f0b6/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/c783/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/ec67/hdl" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/56ae/hdl/src/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+/home/huy_k66/apps/tools/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_13 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_24 -l blk_mem_gen_v8_4_8 -l iomodule_v3_1_10 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_31 -l axi_vip_v1_1_17 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l lib_bmg_v1_0_17 -l axi_traffic_gen_v3_0_17 -l util_vector_logic_v2_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_cdma_v4_1_31 \
"../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/e2d2/hdl/xlconstant_v1_1_vl_rfs.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/f0b6/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/c783/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/ec67/hdl" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/56ae/hdl/src/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+/home/huy_k66/apps/tools/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_13 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_24 -l blk_mem_gen_v8_4_8 -l iomodule_v3_1_10 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_31 -l axi_vip_v1_1_17 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l lib_bmg_v1_0_17 -l axi_traffic_gen_v3_0_17 -l util_vector_logic_v2_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_cdma_v4_1_31 \
"../../../bd/memory_system/ip/memory_system_smartconnect_0_0/sim/memory_system_smartconnect_0_0.v" \
"../../../bd/memory_system/sim/memory_system.v" \

vlog -work dist_mem_gen_v8_0_15  -v2k5 "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/f0b6/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/c783/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/ec67/hdl" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/56ae/hdl/src/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+/home/huy_k66/apps/tools/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_13 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_24 -l blk_mem_gen_v8_4_8 -l iomodule_v3_1_10 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_31 -l axi_vip_v1_1_17 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l lib_bmg_v1_0_17 -l axi_traffic_gen_v3_0_17 -l util_vector_logic_v2_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_cdma_v4_1_31 \
"../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/fa7e/simulation/dist_mem_gen_v8_0.v" \

vcom -work lib_bmg_v1_0_17 -  \
"../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/3f29/hdl/lib_bmg_v1_0_rfs.vhd" \

vcom -work axi_traffic_gen_v3_0_17 -  \
"../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/56ae/hdl/axi_traffic_gen_v3_0_rfs.vhd" \

vlog -work axi_traffic_gen_v3_0_17  -v2k5 "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/f0b6/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/c783/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/ec67/hdl" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/56ae/hdl/src/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+/home/huy_k66/apps/tools/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_13 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_24 -l blk_mem_gen_v8_4_8 -l iomodule_v3_1_10 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_31 -l axi_vip_v1_1_17 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l lib_bmg_v1_0_17 -l axi_traffic_gen_v3_0_17 -l util_vector_logic_v2_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_cdma_v4_1_31 \
"../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/56ae/hdl/axi_traffic_gen_v3_0_rfs.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/f0b6/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/c783/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/ec67/hdl" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/56ae/hdl/src/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+/home/huy_k66/apps/tools/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_13 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_24 -l blk_mem_gen_v8_4_8 -l iomodule_v3_1_10 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_31 -l axi_vip_v1_1_17 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l lib_bmg_v1_0_17 -l axi_traffic_gen_v3_0_17 -l util_vector_logic_v2_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_cdma_v4_1_31 \
"../../../bd/memory_system/ip/memory_system_axi_traffic_gen_0_0/sim/memory_system_axi_traffic_gen_0_0.v" \

vlog -work util_vector_logic_v2_0_4  -v2k5 "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/f0b6/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/c783/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/ec67/hdl" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/56ae/hdl/src/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+/home/huy_k66/apps/tools/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_13 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_24 -l blk_mem_gen_v8_4_8 -l iomodule_v3_1_10 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_31 -l axi_vip_v1_1_17 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l lib_bmg_v1_0_17 -l axi_traffic_gen_v3_0_17 -l util_vector_logic_v2_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_cdma_v4_1_31 \
"../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/fd7b/hdl/util_vector_logic_v2_0_vl_rfs.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/f0b6/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/c783/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/ec67/hdl" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/56ae/hdl/src/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+/home/huy_k66/apps/tools/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_13 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_24 -l blk_mem_gen_v8_4_8 -l iomodule_v3_1_10 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_31 -l axi_vip_v1_1_17 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l lib_bmg_v1_0_17 -l axi_traffic_gen_v3_0_17 -l util_vector_logic_v2_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_cdma_v4_1_31 \
"../../../bd/memory_system/ip/memory_system_util_vector_logic_0_0/sim/memory_system_util_vector_logic_0_0.v" \

vcom -work lib_pkg_v1_0_4 -  \
"../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/8c68/hdl/lib_pkg_v1_0_rfs.vhd" \

vcom -work lib_srl_fifo_v1_0_4 -  \
"../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/1e5a/hdl/lib_srl_fifo_v1_0_rfs.vhd" \

vlog -work fifo_generator_v13_2_10  -v2k5 "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/f0b6/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/c783/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/ec67/hdl" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/56ae/hdl/src/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+/home/huy_k66/apps/tools/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_13 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_24 -l blk_mem_gen_v8_4_8 -l iomodule_v3_1_10 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_31 -l axi_vip_v1_1_17 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l lib_bmg_v1_0_17 -l axi_traffic_gen_v3_0_17 -l util_vector_logic_v2_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_cdma_v4_1_31 \
"../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/1443/simulation/fifo_generator_vlog_beh.v" \

vcom -work fifo_generator_v13_2_10 -  \
"../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/1443/hdl/fifo_generator_v13_2_rfs.vhd" \

vlog -work fifo_generator_v13_2_10  -v2k5 "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/f0b6/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/c783/hdl/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/ec67/hdl" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/56ae/hdl/src/verilog" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/rtl/map" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/ip_top" "+incdir+../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/rtl/cal" "+incdir+/home/huy_k66/apps/tools/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l microblaze_v11_0_13 -l xil_defaultlib -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l lmb_v10_v3_0_14 -l lmb_bram_if_cntlr_v4_0_24 -l blk_mem_gen_v8_4_8 -l iomodule_v3_1_10 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_31 -l axi_vip_v1_1_17 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l lib_bmg_v1_0_17 -l axi_traffic_gen_v3_0_17 -l util_vector_logic_v2_0_4 -l lib_pkg_v1_0_4 -l lib_srl_fifo_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_cdma_v4_1_31 \
"../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/1443/hdl/fifo_generator_v13_2_rfs.v" \

vcom -work lib_fifo_v1_0_19 -  \
"../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/0a12/hdl/lib_fifo_v1_0_rfs.vhd" \

vcom -work axi_datamover_v5_1_33 -  \
"../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/bf20/hdl/axi_datamover_v5_1_vh_rfs.vhd" \

vcom -work axi_sg_v4_1_18 -  \
"../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/6f54/hdl/axi_sg_v4_1_rfs.vhd" \

vcom -work axi_cdma_v4_1_31 -  \
"../../../../mint_ddr4_mig.gen/sources_1/bd/memory_system/ipshared/0b3d/hdl/axi_cdma_v4_1_vh_rfs.vhd" \

vcom -work xil_defaultlib -  \
"../../../bd/memory_system/ip/memory_system_axi_cdma_0_0/sim/memory_system_axi_cdma_0_0.vhd" \

vlog -work xil_defaultlib \
"glbl.v"

