# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Downloads/alveo-u250-xdc.xdc

# Block Designs: bd/memory_system/memory_system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==memory_system || ORIG_REF_NAME==memory_system} -quiet] -quiet

# IP: bd/memory_system/ip/memory_system_ddr4_0_0/memory_system_ddr4_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==memory_system_ddr4_0_0 || ORIG_REF_NAME==memory_system_ddr4_0_0} -quiet] -quiet

# IP: bd/memory_system/ip/memory_system_smartconnect_0_0/memory_system_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==memory_system_smartconnect_0_0 || ORIG_REF_NAME==memory_system_smartconnect_0_0} -quiet] -quiet

# IP: bd/memory_system/ip/memory_system_axi_traffic_gen_0_0/memory_system_axi_traffic_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==memory_system_axi_traffic_gen_0_0 || ORIG_REF_NAME==memory_system_axi_traffic_gen_0_0} -quiet] -quiet

# IP: bd/memory_system/ip/memory_system_xlconstant_0_0/memory_system_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==memory_system_xlconstant_0_0 || ORIG_REF_NAME==memory_system_xlconstant_0_0} -quiet] -quiet

# XDC: /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/memory_system_ooc.xdc
