# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.runs/synth_1/top_u250.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param bd.open.in_stealth_mode 1
set_msg_config  -id {[BD 41-1306]}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
set_msg_config  -id {[BD 41-1306]}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
set_msg_config  -id {[BD 41-1306]}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xcu250-figd2104-2L-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.cache/wt [current_project]
set_property parent.project_path /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.xpr [current_project]
set_property XPM_LIBRARIES {XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:au250:part0:1.3 [current_project]
set_property ip_output_repo /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.srcs/sources_1/bd/memory_system/ip/atg_data.coe
add_files /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.srcs/sources_1/bd/memory_system/ip/atg_addr.coe
read_verilog -library xil_defaultlib {
  /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/hdl/memory_system_wrapper.v
  /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.srcs/sources_1/new/top_u250.v
}
add_files /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.srcs/sources_1/bd/memory_system/memory_system.bd
set_property used_in_implementation false [get_files -all /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/bd_0/ip/ip_0/bd_021b_microblaze_I_0.xdc]
set_property used_in_implementation false [get_files -all /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/bd_0/ip/ip_0/bd_021b_microblaze_I_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/bd_0/ip/ip_1/bd_021b_rst_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/bd_0/ip/ip_1/bd_021b_rst_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/bd_0/ip/ip_2/bd_021b_ilmb_0.xdc]
set_property used_in_implementation false [get_files -all /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/bd_0/ip/ip_3/bd_021b_dlmb_0.xdc]
set_property used_in_implementation false [get_files -all /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/bd_0/ip/ip_6/bd_021b_lmb_bram_I_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/bd_0/ip/ip_9/bd_021b_second_lmb_bram_I_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/bd_0/ip/ip_10/bd_021b_iomodule_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/bd_0/bd_021b_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/ip_0/memory_system_ddr4_0_0_microblaze_mcs_board.xdc]
set_property used_in_implementation false [get_files -all /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/ip_0/memory_system_ddr4_0_0_microblaze_mcs_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/ip_1/par/memory_system_ddr4_0_0_phy_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/memory_system_ddr4_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/par/memory_system_ddr4_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_smartconnect_0_0/bd_0/ip/ip_0/bd_ee24_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_smartconnect_0_0/bd_0/ip/ip_1/bd_ee24_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_smartconnect_0_0/bd_0/ip/ip_2/bd_ee24_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_smartconnect_0_0/bd_0/ip/ip_3/bd_ee24_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_smartconnect_0_0/bd_0/ip/ip_4/bd_ee24_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_smartconnect_0_0/bd_0/ip/ip_8/bd_ee24_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_smartconnect_0_0/bd_0/ip/ip_9/bd_ee24_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_smartconnect_0_0/bd_0/ip/ip_9/bd_ee24_sawn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_smartconnect_0_0/bd_0/ip/ip_10/bd_ee24_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_smartconnect_0_0/bd_0/ip/ip_10/bd_ee24_swn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_smartconnect_0_0/bd_0/ip/ip_11/bd_ee24_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_smartconnect_0_0/bd_0/ip/ip_11/bd_ee24_sbn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_smartconnect_0_0/bd_0/ip/ip_12/bd_ee24_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_smartconnect_0_0/bd_0/ip/ip_13/bd_ee24_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_smartconnect_0_0/bd_0/ip/ip_13/bd_ee24_m00awn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_smartconnect_0_0/bd_0/ip/ip_14/bd_ee24_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_smartconnect_0_0/bd_0/ip/ip_14/bd_ee24_m00wn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_smartconnect_0_0/bd_0/ip/ip_15/bd_ee24_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_smartconnect_0_0/bd_0/ip/ip_15/bd_ee24_m00bn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_smartconnect_0_0/bd_0/ip/ip_17/bd_ee24_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_smartconnect_0_0/bd_0/ip/ip_18/bd_ee24_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_smartconnect_0_0/bd_0/ip/ip_18/bd_ee24_m01awn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_smartconnect_0_0/bd_0/ip/ip_19/bd_ee24_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_smartconnect_0_0/bd_0/ip/ip_19/bd_ee24_m01wn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_smartconnect_0_0/bd_0/ip/ip_20/bd_ee24_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_smartconnect_0_0/bd_0/ip/ip_20/bd_ee24_m01bn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_smartconnect_0_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_smartconnect_0_0/smartconnect.xdc]
set_property used_in_implementation false [get_files -all /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_axi_traffic_gen_0_0/memory_system_axi_traffic_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/memory_system_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/bd_0/ip/ip_0/data/mb_bootloop_le.elf]
set_property used_in_implementation false [get_files -all /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/ip_0/mb_bootloop_le.elf]
set_property used_in_implementation false [get_files -all /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.gen/sources_1/bd/memory_system/ip/memory_system_ddr4_0_0/sw/calibration_0/Debug/calibration_ddr.elf]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.srcs/constrs_1/imports/Downloads/alveo-u250-xdc.xdc
set_property used_in_implementation false [get_files /home/huy_k66/Documents/dma_vivado/20241/mint_ddr4_mig/mint_ddr4_mig.srcs/constrs_1/imports/Downloads/alveo-u250-xdc.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top top_u250 -part xcu250-figd2104-2L-e
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_u250.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file top_u250_utilization_synth.rpt -pb top_u250_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
